services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=pass
  
  rabbit:
    image: rabbitmq:latest
    hostname: rabbit
    ports:
      - "5672"
      - "15692"
  log:
    image: dyn-conf:latest
    build:
      context: src/dyn-config
      dockerfile: src/dyn-config.Dockerfile
    ports:
      - "9090"

  conf:
    image: logger
    build:
      context: src/logger
      dockerfile: stc/logger.Dockerfile
    ports:
      - "8000"
