services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=pass
  
  rabbit:
    image: rabbitmq:latest
    hostname: rabbit
    ports:
      - "5672"
      - "15672"
