services:
  # Project containers

  monad-queue:
    image: monad-queue
    build:
      context: src/monads
      dockerfile: src/monads.Dockerfile
    ports:
      - "8901"

  log:
    image: dyn-conf:latest
    build:
      context: src/dyn-config
      dockerfile: src/dyn-config.Dockerfile
    ports:
      - "9090"

  conf:
    image: logger
    build:
      context: src/logger
      dockerfile: stc/logger.Dockerfile
    ports:
      - "8000"

  # Infrastructure containers
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=pass
  
  rabbit:
    image: rabbitmq:latest
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15692:15692"
